# sudo access super user acess is required by travis
sudo: required

# A copy of docker CLI is required
services:
  - docker

# Before running the tests or deploy, below are required
# 1. Build the docker image from Dockerfile.dev and tag it.
before_install:
  -  docker build -t pbdavala/docker-react -f Dockerfile.dev .

# Define the scripts to be run to test
script:
  - docker run -e CI=true pbdavala/frontend npm run test -- --coverage
