# This is used for running elasticbeanstalk application called "frontend" in pavan-saa AWS account.
version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile    # This Dockerfile uses bulider and run phases the latter using nginx
    ports:
      - "80:80"
