# specify a base image. Use the node docker image which is alpine. (minimal)
FROM node:alpine

#work dir setup in the container. Will be created if does not exist
WORKDIR '/app'

# Copy only package.json from current workdir "frontend" to the current workdir inside container.
COPY package.json .

# Install some dependencies
RUN npm install

# Copy NOW everything from current workdir "frontend" to the current workdir inside container.
#Optional now because docker-compose.yml has a volume step .:/app  Leave it to be safe if no docker-compose
COPY . .         

# Default RUN Command
CMD ["npm", "run", "start"]
